package it.nextsw.olingo.edmextension.annotation;


import org.apache.olingo.odata2.api.annotation.edm.EdmFacets;
import org.apache.olingo.odata2.api.edm.EdmSimpleTypeKind;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation utilizzata per definire le proprietà edm su classi annotate con {@link org.apache.olingo.odata2.api.annotation.edm.EdmComplexType}
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface EdmSimpleProperty {

    EdmSimpleTypeKind type() default EdmSimpleTypeKind.Null;

    /**
     * Define the name for the Property.
     * If not set a default value has to be generated by the EDM provider.
     *
     * @return name for the Property
     */
    String name() default "";

    /**
     * Define the EdmFacets for the Property in the EDM.
     * If not set the default EdmFacet values are used (see {@link EdmFacets}).
     *
     * @return facets for the Property as used in the EDM
     */
    EdmFacets facets() default @EdmFacets;
}
